name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']
        django-version: [2.2, 3.1, 3.2, 4.0]
        exclude:
        # Django 4.0 doesn't support Python 3.7
        - python-version: 3.7
          django-versio: 4.0
        # Django 2.2 doesn't support Python 3.10
        - python-version: 3.10
          django-version: 2.2
        # Django 3.1 doesn't support Python 3.10
        - python-version: 3.10
          django-version: 3.1


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -q Django==${{ matrix.django-version }}
          pip install -r requirements.txt
          pip install tox-gh-actions
      - name: Run tests
        run: |
          tox
